### ISSUE TITLE
How would you go about rendering an arpeggio rather than a chord?

### ISSUE THREAD

**Issue by 7sharp9** [cemolcay/Fretboard#4]

**Comment by cemolcay** [comment]
you should probably set the **x** position of the notes in the chord with an offset like 10 or 15 points. it would be a nice feature for this library, so PRs are welcome 👍

**Comment by 7sharp9** [comment]
Im not sure if that approach would work, for arpeggios you can have more than one note per string, like this is a common pattern:

<img width="220" alt="screen shot 2018-03-24 at 10 13 13" src="https://user-images.githubusercontent.com/588746/37862826-9da66132-2f4b-11e8-9888-43c3b5d2a0a3.png">

**Comment by 7sharp9** [comment]
And sometimes arpeggios have skipped strings:

<img width="325" alt="screen shot 2018-03-24 at 10 20 52" src="https://user-images.githubusercontent.com/588746/37862906-ae9b006e-2f4c-11e8-952b-a16352300148.png">

I know this is not a digram but you should get the idea.

Another expansion aspect could be having the music notation above the diagram too.
